name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to let the runner save the image file to your repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=Gha8&layout=compact&theme=vision-dark
          token: ${{ secrets.GITHUB_TOKEN }}
          path: top-langs.svg # Saves it right to your root directory

      - name: Deploy to repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
